version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      # Clean environment and cache
      - run:
          name: Clean Environment
          command: |
            rm -rf venv
            rm -rf .tox
            pip cache purge || true

      # Restore cached dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}-{{ checksum "typing_requirements.txt" }}
            - v2-dependencies-

      # Set up Python environment and install dependencies
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir tox
            pip install --no-cache-dir -r requirements.txt
            pip install --no-cache-dir -r test_requirements.txt
            pip install --no-cache-dir -r typing_requirements.txt
            pip install --no-cache-dir ./model-pkg/model_abandono-0.0.1-py3-none-any.whl

      # Save cache with new version key
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}-{{ checksum "typing_requirements.txt" }}

      # Run code quality checks
      - run:
          name: Run Code Quality Checks
          command: |
            . venv/bin/activate
            tox -e checks

      # Clean tox environment before tests
      - run:
          name: Clean Tox Environment
          command: |
            . venv/bin/activate
            rm -rf .tox

      # Run tests
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            tox -e test_app

      # Store test results
      - store_test_results:
          path: test-results

      # Store artifacts
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
