version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.10
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install scikit-learn==1.3.2

jobs:
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '20.9'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Railway Login and Project Setup
          command: |
            cd bankchurn-api
            RAILWAY_TOKEN="${fd797f9c-ee90-4e19-bdbd-dc93e35b6dad}" railway link --project ${R7fc494bf-a669-484b-b368-ffff9d005361}
          no_output_timeout: 10m    
      - run:
          name: Deploy to Railway
          command: |
            cd bankchurn-api
            # Remove any existing service selection
            railway service
            # Deploy with explicit project and service
            RAILWAY_TOKEN="${fd797f9c-ee90-4e19-bdbd-dc93e35b6dad}" railway up \
              --project ${7fc494bf-a669-484b-b368-ffff9d005361} \
              --service radiant-joy \
              --detach \
              --timeout 20m
          no_output_timeout: 30m

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 1
  deploy_pipeline:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only:
                - main
